@schema = http
@hostname = localhost
@backend = {{schema}}://{{hostname}}:3000
@musicapi = api/v1/music

###

GET {{backend}}/{{musicapi}}/

###

GET {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec

###

POST {{backend}}/{{musicapi}}
Content-Type: application/json
Prefer: return=representation

{
    "name": "oi",
    "artist": "oi",
    "image": "https://www.example.com/some/dir/somefile.png",
    "songs": [
        {
            "number": 1,
            "title": "it is what it is"
        },
        {
            "number": 2,
            "title": "it is what it is not"
        }
    ]
}

###

DELETE {{backend}}/{{musicapi}}/626017d3196044bd6a3a8941


###

PATCH {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec
Content-Type: application/json
Prefer: return=Minimal

{
    "rating": 2,
    "favorite": true
}

###

PATCH {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec
Content-Type: application/json

{
    "favorite": true
}