@schema = http
@hostname = localhost
@backend = {{schema}}://{{hostname}}:4000
@musicapi = api/v1/music

###

GET {{backend}}/{{musicapi}}/

###

GET {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec

###

POST {{backend}}/{{musicapi}}
Content-Type: application/json
Prefer: return=representation

{
    "name": "Appetite for Destruction",
    "artist": "Guns N' Roses",
    "image": "https://www.example.com/some/dir/somefile.png",
    "songs": [
        {
            "number": 1,
            "title": "Paradise City"
        },
        {
            "number": 2,
            "title": "Sweet Child of Mine"
        }
    ]
}

###

DELETE {{backend}}/{{musicapi}}/626e582cd8b5fde831ef987c


###

PATCH {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec
Content-Type: application/json
Prefer: return=Minimal

{
    "rating": 4,
    "favorite": false
}

###

PATCH {{backend}}/{{musicapi}}/62612635ffb8d418d8700fec
Content-Type: application/json

{
    "favorite": true
}